name: Odds

on:
  push:
    branches: [master]

concurrency:
  group: odds-${{ github.head_ref }}
  cancel-in-progress: true

env:
  PYTHONUNBUFFERED: "1"
  FORCE_COLOR: "1"

jobs:
  run:
    name: Evaluating Basic Strategy Odds
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install Hatch
      run: pip install --upgrade hatch

    - name: Run Simulation
      working-directory: ./python
      run: hatch run odds